# Generated by Django 5.1.2 on 2025-02-13 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_menu', '0002_cart_dailyreport_stafflogin_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='token',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
