# Generated by Django 5.1.2 on 2025-02-15 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_menu', '0004_staffnotification_alter_token_current_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='token',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='staffnotification',
            name='token',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
