# Generated by Django 5.1.2 on 2025-02-15 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_menu', '0005_alter_cart_token_alter_staffnotification_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='token',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='order',
            name='token',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='staffnotification',
            name='token',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
