# Generated by Django 5.1.2 on 2025-02-16 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_menu', '0006_alter_cart_token_alter_order_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='token',
            field=models.CharField(max_length=255),
        ),
    ]
