# Generated by Django 5.1.2 on 2025-02-16 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_menu', '0007_alter_cart_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='token',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
