# Generated by Django 5.1.2 on 2025-02-21 14:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_menu', '0009_remove_staffnotification_message_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StaffNotification',
        ),
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
