# Generated by Django 5.1.2 on 2025-02-22 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_menu', '0011_monthlyreport'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MonthlyReport',
        ),
        migrations.AddField(
            model_name='dailyreport',
            name='is_monthly',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dailyreport',
            name='month',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dailyreport',
            name='year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='dailyreport',
            unique_together={('date', 'is_monthly'), ('month', 'year', 'is_monthly')},
        ),
    ]
