# Generated by Django 5.1.2 on 2025-02-22 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_menu', '0012_delete_monthlyreport_dailyreport_is_monthly_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dailyreport',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='dailyreport',
            name='is_monthly',
        ),
        migrations.RemoveField(
            model_name='dailyreport',
            name='month',
        ),
        migrations.RemoveField(
            model_name='dailyreport',
            name='year',
        ),
    ]
