# Generated by Django 5.1.2 on 2025-02-22 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_menu', '0014_monthlyreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlyreport',
            name='orders',
            field=models.ManyToManyField(blank=True, to='restaurant_menu.order'),
        ),
    ]
