# Generated by Django 5.1.2 on 2025-02-22 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_menu', '0015_monthlyreport_orders'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MonthlyReport',
        ),
    ]
