# Generated by Django 5.1.2 on 2025-02-22 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_menu', '0016_delete_monthlyreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyreport',
            name='is_monthly',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dailyreport',
            name='month',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dailyreport',
            name='year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
