# Generated by Django 5.1.2 on 2025-03-04 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_menu', '0017_dailyreport_is_monthly_dailyreport_month_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='started_cooking_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('', 'No Status'), ('progress', 'Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='', max_length=20),
        ),
    ]
